### ISSUE TITLE
Recommendation

### ISSUE THREAD

**Issue by DollyVolley** [calledit/the_mind#2]
Nice journey! Maybe you'd like to watch this as well: https://www.youtube.com/watch?v=xRel1JKOEbI

**Comment by calledit** [comment]
Thank you, I did not really expect anyone to read this.
It is more like my own story which I write to help myself understand how things work.

I am not a big fan of _integrated information theory_ which he goes in to in the lecture, but there where other parts of the lecture that have certain merit.

Anyway thanks for the feedback, much appreciated!

May I ask how you found this page?
